vinsert.c
int detectLength(char **List)
Referenced by vinsert, main.
void vinsert(char **List, char *string)
References detectLength.
Referenced by main.
int main()
References detectLength, vinsert.