.TH "vinsert.c" 3 "Tue Apr 11 2017" "myproj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vinsert.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdetectLength\fP (char **List)"
.br
.ti -1c
.RI "void \fBvinsert\fP (char **List, char *string)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int detectLength (char ** List)"

.PP
Definition at line 7 of file vinsert\&.c\&.
.SS "int main ()"

.PP
Definition at line 35 of file vinsert\&.c\&.
.SS "void vinsert (char ** List, char * string)"

.PP
Definition at line 17 of file vinsert\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for myproj from the source code\&.
